## DataFrame objects

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Year": list(range(2015, 2020)),
    "Observation": [123, 39, 31, 69, 110]
})

df

   Year  Observation
0  2015          123
1  2016           39
2  2017           31
3  2018           69
4  2019          110

In [6]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
df.columns

Index(['Year', 'Observation'], dtype='str')

In [ ]:
# type(df["Year"])
df["Year"]

0    2015
1    2016
2    2017
3    2018
4    2019
Name: Year, dtype: int64

In [13]:
year_df = df.set_index("Year")
year_df

      Observation
Year
2015          123
2016           39
2017           31
2018           69
2019          110

In [14]:
repr(pd.Timestamp("2020-01"))

"Timestamp('2020-01-01 00:00:00')"

In [15]:
repr(pd.Period("2020-01"))

"Period('2020-01', 'M')"

In [16]:
print(repr(pd.Timestamp("2020")))
print(repr(pd.Timestamp("2020-01-01 12:34")))
print(repr(pd.Period("2020-01-01")))
print(repr(pd.Period("2020-01-01", freq="M")))

Timestamp('2020-01-01 00:00:00')
Timestamp('2020-01-01 12:34:00')
Period('2020-01-01', 'D')
Period('2020-01', 'M')